import type { DesignConfig } from "./types";
import { DEFAULT_CONFIG } from "./types";
import { backgroundPreview } from "./backgrounds";

function preset(
  id: string,
  name: string,
  patch: Partial<DesignConfig> & { background: DesignConfig["background"] },
): { id: string; name: string; config: DesignConfig } {
  return {
    id,
    name,
    config: { ...structuredClone(DEFAULT_CONFIG), ...patch },
  };
}

export const PRESETS = [
  preset("saffron-dawn", "Saffron Dawn", {
    background: { kind: "gradient", value: "saffron-dawn" },
    fonts: { sanskrit: "yatra", latin: "sans" },
    sizes: { sanskrit: 48, translation: 27 },
    colors: { text: "#fffaf0", muted: "#ffe9c4", accent: "#ffd700", footer: "#ffdf9e" },
    layout: "centered",
    decoration: "om",
    ornament: "flourish",
    frame: true,
    glow: true,
    grain: true,
    vignette: true,
    padding: 104,
  }),
  preset("temple-maroon", "Temple Maroon", {
    background: { kind: "gradient", value: "temple-maroon" },
    fonts: { sanskrit: "tiro", latin: "sans" },
    sizes: { sanskrit: 46, translation: 26 },
    colors: { text: "#fef2f2", muted: "#fdd7c6", accent: "#fbbf24", footer: "#fca5a5" },
    layout: "centered",
    decoration: "om",
    ornament: "flourish",
    frame: true,
    glow: true,
    vignette: true,
    padding: 100,
  }),
  preset("midnight-gold", "Midnight Gold", {
    background: { kind: "gradient", value: "midnight" },
    fonts: { sanskrit: "tiro", latin: "sans" },
    sizes: { sanskrit: 46, translation: 27 },
    colors: { text: "#ffffff", muted: "#dfe3ff", accent: "#ffcc66", footer: "#a5b4fc" },
    layout: "centered",
    decoration: "om",
    ornament: "flourish",
    frame: true,
    glow: true,
    grain: true,
    vignette: true,
    letterSpacing: 2,
    padding: 104,
  }),
  preset("royal-purple", "Royal Purple", {
    background: { kind: "gradient", value: "royal-purple" },
    fonts: { sanskrit: "tiro", latin: "sans" },
    sizes: { sanskrit: 46, translation: 26 },
    colors: { text: "#fbf5ff", muted: "#e9d8fd", accent: "#ffd76a", footer: "#d8b4fe" },
    layout: "centered",
    decoration: "om",
    ornament: "flourish",
    frame: true,
    glow: true,
    vignette: true,
    padding: 100,
  }),
  preset("krishna-blue", "Krishna Blue", {
    background: { kind: "gradient", value: "krishna-blue" },
    fonts: { sanskrit: "noto", latin: "sans" },
    sizes: { sanskrit: 48, translation: 26 },
    colors: { text: "#ffffff", muted: "#cfe8ff", accent: "#8de6f5", footer: "#93c5fd" },
    layout: "verse-first",
    decoration: "none",
    ornament: "flourish",
    frame: false,
    glow: true,
    vignette: true,
    padding: 96,
  }),
  preset("sacred-emerald", "Sacred Emerald", {
    background: { kind: "gradient", value: "emerald" },
    fonts: { sanskrit: "yatra", latin: "sans" },
    sizes: { sanskrit: 46, translation: 26 },
    colors: { text: "#ecfdf5", muted: "#b7efd1", accent: "#fbbf24", footer: "#6ee7b7" },
    layout: "centered",
    decoration: "floral",
    ornament: "flourish",
    frame: true,
    glow: true,
    vignette: true,
    padding: 100,
  }),
  preset("gold-on-black", "Gold on Black", {
    background: { kind: "solid", value: "#050505" },
    fonts: { sanskrit: "yatra", latin: "sans" },
    sizes: { sanskrit: 48, translation: 27 },
    colors: { text: "#ffd700", muted: "#e8e6e1", accent: "#ffd700", footer: "#8a8172" },
    layout: "centered",
    decoration: "om",
    ornament: "flourish",
    frame: true,
    glow: true,
    grain: true,
    vignette: true,
    letterSpacing: 2,
    padding: 104,
  }),
  preset("obsidian", "Obsidian Luxe", {
    background: { kind: "gradient", value: "obsidian" },
    fonts: { sanskrit: "tiro", latin: "serif" },
    sizes: { sanskrit: 50, translation: 24 },
    colors: { text: "#f5f1e8", muted: "#cfc7b8", accent: "#c9a96a", footer: "#9a8f7a" },
    layout: "big-quote",
    decoration: "none",
    ornament: "double",
    frame: false,
    glow: true,
    grain: true,
    vignette: true,
    padding: 104,
  }),
  preset("paper-scroll", "Paper Scroll", {
    background: { kind: "gradient", value: "paper-fade" },
    fonts: { sanskrit: "tiro", latin: "serif" },
    sizes: { sanskrit: 44, translation: 26 },
    colors: { text: "#3f2d1d", muted: "#6d5638", accent: "#a16207", footer: "#7c6a53" },
    layout: "centered",
    decoration: "floral",
    ornament: "flourish",
    frame: true,
    glow: true,
    grain: false,
    vignette: false,
    padding: 100,
  }),
  preset("ivory-minimal", "Ivory Minimal", {
    background: { kind: "solid", value: "#faf6ee" },
    fonts: { sanskrit: "tiro", latin: "serif" },
    sizes: { sanskrit: 44, translation: 27 },
    colors: { text: "#221f1a", muted: "#57503f", accent: "#b08d57", footer: "#8a8172" },
    layout: "centered",
    decoration: "none",
    ornament: "double",
    frame: false,
    glow: false,
    grain: false,
    vignette: false,
    padding: 104,
  }),
  preset("charcoal-minimal", "Charcoal Minimal", {
    background: { kind: "solid", value: "#18181b" },
    fonts: { sanskrit: "noto", latin: "serif" },
    sizes: { sanskrit: 46, translation: 26 },
    colors: { text: "#f4f4f5", muted: "#a1a1aa", accent: "#d4d4d8", footer: "#71717a" },
    layout: "centered",
    decoration: "none",
    ornament: "double",
    frame: false,
    glow: false,
    grain: false,
    vignette: false,
    padding: 104,
  }),
  preset("rose-blush", "Rose Blush", {
    background: { kind: "gradient", value: "rose" },
    fonts: { sanskrit: "tiro", latin: "serif" },
    sizes: { sanskrit: 42, translation: 25 },
    colors: { text: "#881337", muted: "#9f1239", accent: "#e11d48", footer: "#be123c" },
    layout: "editorial-left",
    alignment: "left",
    decoration: "floral",
    ornament: "flourish",
    frame: false,
    glow: true,
    vignette: false,
    padding: 96,
  }),
  preset("ocean-teal", "Ocean Teal", {
    background: { kind: "gradient", value: "ocean" },
    fonts: { sanskrit: "yatra", latin: "sans" },
    sizes: { sanskrit: 46, translation: 28 },
    colors: { text: "#f0fdfa", muted: "#a5f3e8", accent: "#5eead4", footer: "#7dedd9" },
    layout: "translation-first",
    decoration: "none",
    ornament: "flourish",
    frame: false,
    glow: true,
    vignette: true,
    padding: 100,
  }),
  preset("photo", "Photo", {
    background: { kind: "photo", value: "" },
    photo: null,
    showOverlay: true,
    photoFilters: { brightness: 100, contrast: 108, saturation: 115, blur: 0, darken: 50 },
    fonts: { sanskrit: "tiro", latin: "sans" },
    sizes: { sanskrit: 44, translation: 26 },
    colors: { text: "#ffffff", muted: "#f2f2f2", accent: "#ffffff", footer: "#e5e5e5" },
    layout: "bottom-third",
    decoration: "none",
    ornament: "flourish",
    frame: false,
    glow: true,
    grain: true,
    vignette: true,
    padding: 96,
  }),
] as const;

export interface TemplateMeta {
  id: string;
  name: string;
  config: DesignConfig;
}

export const TEMPLATES: TemplateMeta[] = PRESETS.map((p) => ({
  id: p.id,
  name: p.name,
  config: structuredClone(p.config),
}));

export function getTemplateById(id: string): DesignConfig | null {
  const t = TEMPLATES.find((t) => t.id === id);
  return t ? structuredClone(t.config) : null;
}

export function templatePreview(id: string): string {
  const t = TEMPLATES.find((t) => t.id === id);
  return t ? backgroundPreview(t.config) : "#0a0a0a";
}
